---
- name: Install Samba
  package:
    name: samba
    state: present
  when: ansible_facts['os_family'] == "Debian"
- name: Configure smb.conf
  template:
    src: ../templates/smb.conf
    dest: /etc/samba/smb.conf.tail
  notify: restart samba

- name: create clean new config
  shell: |-
    cp /usr/share/samba/smb.conf /etc/samba/smb.conf

- name: add smb.conf.tail
  shell: |-
    cat /etc/samba/smb.conf.tail >> /etc/samba/smb.conf

- name: create share dirs
  shell: |-
    mkdir -p /srv/samba/share && chown nobody:nogroup /srv/samba/share/

- name: restart samba
  service:
    name: smbd
    state: restarted

- name: restart samba
  service:
    name: nmbd
    state: restarted
